In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [10]:
ann = tf.keras.models.Sequential()

In [11]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [13]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [14]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100


250/250 [==============================] - 1s 2ms/step - loss: 0.5122 - accuracy: 0.7876
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4513 - accuracy: 0.7970
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4297 - accuracy: 0.8140
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4161 - accuracy: 0.8251
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4047 - accuracy: 0.8314
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3923 - accuracy: 0.8378
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3779 - accuracy: 0.8447
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3656 - accuracy: 0.8493
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3578 - accuracy: 0.8534
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3537 - accu

In [16]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

1/1 [==============================] - 0s 206ms/step


array([[0.02743384]], dtype=float32)

In [17]:
y_pred = ann.predict(X_test)
y_pred

63/63 [==============================] - 0s 2ms/step


array([[0.24311021],
       [0.3408206 ],
       [0.1140068 ],
       ...,
       [0.2907091 ],
       [0.18886983],
       [0.2536114 ]], dtype=float32)

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1507   88]
 [ 186  219]]
0.863
